databases:
  - name: odin_book
    databaseName: odin_book
    user: odin_book
    plan: free

services:
  - type: web
    name: odin_book
    env: ruby
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: odin_book
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
